import IMG1 from "../../../../assets/E-comerce.jpeg";
import IMG2 from "../../../../assets/Api-cripto.jpeg";
import IMG3 from "../../../../assets/landing.jpeg";
import IMG4 from "../../../../assets/Grafico-Btc.jpeg";
import IMG5 from "../../../../assets/Crud.jpeg";
import IMG6 from "../../../../assets/Sociapedia.jpeg";
import IMG7 from "../../../../assets/filterstate.jpeg";
import IMG8 from "../../../../assets/todoapp.jpeg";
import IMG9 from "../../../../assets/Macbookpro.jpeg";
export { IMG1, IMG2, IMG3, IMG4, IMG5, IMG6, IMG7, IMG8, IMG9 };
